const keywordMap = {
  // Home
  home: 'Home',
  homepage: 'Home',
  main: 'Home',
  start: 'Home',
  hme: 'Home',
  hom: 'Home',
  hoem: 'Home',

  // About
  about: 'About',
  abot: 'About',
  abt: 'About',
  company: 'About',
  compny: 'About',
  info: 'About',
  infomation: 'About',
  team: 'About',
  teem: 'About',
  story: 'About',
  histroy: 'About',

  sculptures: 'Shop',
  sculpture: 'Shop',
  sculture: 'Shop',
  sculpure: 'Shop',
  sculptur: 'Shop',
  statue: 'Shop',
  stattu: 'Shop',
  statoo: 'Shop',
  art: 'Shop',
  arte: 'Shop',
  stone: 'Shop',
  ston: 'Shop',
  clay: 'Shop',
  claay: 'Shop',
  carving: 'Shop',
  craving: 'Shop',

  shop: 'Shop',
  shopp: 'Shop',
  shpo: 'Shop',
  shp: 'Shop',
  buy: 'Shop',
  purchase: 'Shop',
  perches: 'Shop',
  store: 'Shop',
  stoore: 'Shop',
  stoor: 'Shop',
  products: 'Shop',
  product: 'Shop',
  items: 'Shop',
  item: 'Shop',
  catalog: 'Shop',
  catlog: 'Shop',
  catologue: 'Shop',
  gardern: 'Shop',
  garden: 'Shop',
  collection: 'Shop',
  decors: 'Shop',
  decor: 'Shop',

  // Work & Architecture
  work: 'Work & Architecture',
  wrk: 'Work & Architecture',
  wrok: 'Work & Architecture',
  architecture: 'Work & Architecture',
  architechture: 'Work & Architecture',
  archi: 'Work & Architecture',
  design: 'Work & Architecture',
  desgin: 'Work & Architecture',
  build: 'Work & Architecture',
  buid: 'Work & Architecture',
  structure: 'Work & Architecture',
  strcture: 'Work & Architecture',
  'work and architecture': 'Work & Architecture',

  // Contact
  contact: 'Contact',
  contct: 'Contact',
  conntact: 'Contact',
  support: 'Contact',
  supprt: 'Contact',
  help: 'Contact',
  hlp: 'Contact',
  reach: 'Contact',
  raech: 'Contact',
  message: 'Contact',
  msg: 'Contact',
  email: 'Contact',
  mail: 'Contact',
  connect: 'Contact',
  conenct: 'Contact',
};

export default keywordMap;
