const keywordMap = {
  // Home
  home: 'Home',
  homepage: 'Home',
  main: 'Home',
  start: 'Home',
  landing: 'Home',
  welcome: 'Home',

  // About
  about: 'About',
  company: 'About',
  info: 'About',
  information: 'About',
  team: 'About',
  story: 'About',
  history: 'About',
  profile: 'About',
  background: 'About',
  mission: 'About',
  vision: 'About',

  // Shop
  sculptures: 'Shop',
  sculpture: 'Shop',
  statue: 'Shop',
  statues: 'Shop',
  art: 'Shop',
  stone: 'Shop',
  clay: 'Shop',
  carving: 'Shop',
  shop: 'Shop',
  buy: 'Shop',
  purchase: 'Shop',
  store: 'Shop',
  product: 'Shop',
  products: 'Shop',
  items: 'Shop',
  item: 'Shop',
  catalog: 'Shop',
  collection: 'Shop',
  garden: 'Shop',
  decor: 'Shop',
  decorations: 'Shop',
  gift: 'Shop',
  gifts: 'Shop',
  handmade: 'Shop',
  artisan: 'Shop',

  // Work & Architecture
  work: 'Work & Architecture',
  architecture: 'Work & Architecture',
  design: 'Work & Architecture',
  build: 'Work & Architecture',
  building: 'Work & Architecture',
  structure: 'Work & Architecture',
  project: 'Work & Architecture',
  projects: 'Work & Architecture',
  planning: 'Work & Architecture',
  model: 'Work & Architecture',

  // Contact
  contact: 'Contact',
  support: 'Contact',
  help: 'Contact',
  reach: 'Contact',
  message: 'Contact',
  email: 'Contact',
  mail: 'Contact',
  connect: 'Contact',
  call: 'Contact',
  phone: 'Contact',
  enquiry: 'Contact',
  inquiry: 'Contact',
  feedback: 'Contact',
  suggestion: 'Contact',
};

export default keywordMap;
